version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: echo "YANDEX_API_KEY=$YANDEX_API_KEY" >> .env  
      - run: yarn test
    deploy:
        filters:
          only: /v[0-9]+(\.[0-9]+)*/
        steps:
        - attach_workspace:
            at: ~/repo
        - run:
            name: Build version
            command: yarn build
            name: Authenticate with registry
            command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            name: Publish package
            command: npm publish
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy
